export const CHANGE_CUSTOMER = "CHANGE_CUSTOMER"
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS"

export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS"
export const CREATE_ACTIVITY_SUCCESS = "CREATE_ACTIVITY_SUCCESS"
export const UPDATE_ACTIVITY_SUCCESS = "UPDATE_ACTIVITY_SUCCESS"