export const CHANGE_CUSTOMER = "CHANGE_CUSTOMER"
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS"
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"

export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS"
export const CREATE_ACTIVITY_SUCCESS = "CREATE_ACTIVITY_SUCCESS"
export const UPDATE_ACTIVITY_SUCCESS = "UPDATE_ACTIVITY_SUCCESS"